//! Shape conformance: our encoded wire payloads must validate against Komga's
//! published OpenAPI request schemas (`spec/komga-v1.json`, generated by Komga
//! itself at build time).
//!
//! Komga serialises camelCase JSON, the engine's default, so no resource sets
//! `case = ...`. Ids are opaque **strings**, so any fixture carrying a `${ref}`
//! must resolve it through [`core_testkit::GuidRefs`] — the default
//! [`core_testkit::DummyRefs`] yields the integer `1` and fails decode with
//! `expected string, got 1`.
//!
//! `${ref}` / `${env}` in fixtures are dummy-resolved; only the resulting shape
//! matters here, not the values.

use core_testkit::{GuidRefs, check, check_with_refs};
use serde_json::Value;

#[allow(unused_imports)]
use komga_v1::resources;

fn spec() -> Value {
    serde_json::from_str(include_str!("../spec/komga-v1.json")).expect("spec parses")
}

/// One conformance test per resource: `check` its `config.yaml` fixture against
/// the named OpenAPI schema. The harness lives in [`core_testkit::check`].
macro_rules! conformance {
    ($name:ident, $ty:path, $schema:literal, $fixture:literal) => {
        #[test]
        fn $name() {
            check::<$ty>(&spec(), $schema, include_str!($fixture));
        }
    };
}

/// Same, for a fixture whose `${ref}` targets a string-id resource.
macro_rules! conformance_guid_refs {
    ($name:ident, $ty:path, $schema:literal, $fixture:literal) => {
        #[test]
        fn $name() {
            check_with_refs::<$ty>(&spec(), $schema, include_str!($fixture), &GuidRefs);
        }
    };
}

conformance!(
    library,
    resources::library::Library,
    "LibraryCreationDto",
    "testdata/library/config.yaml"
);
conformance_guid_refs!(
    user,
    resources::user::User,
    "UserCreationDto",
    "testdata/user/config.yaml"
);
conformance!(
    settings,
    resources::settings::Settings,
    "SettingsUpdateDto",
    "testdata/settings/config.yaml"
);
conformance!(
    api_key,
    resources::api_key::ApiKey,
    "ApiKeyRequestDto",
    "testdata/api_key/config.yaml"
);
conformance!(
    client_setting_global,
    resources::client_setting_global::ClientSettingGlobal,
    "ClientSettingGlobalUpdateDto",
    "testdata/client_setting_global/config.yaml"
);
conformance!(
    client_setting_user,
    resources::client_setting_user::ClientSettingUser,
    "ClientSettingUserUpdateDto",
    "testdata/client_setting_user/config.yaml"
);
